@echo off

echo Analyze raw HTTP tcpdump trace
echo.
..\bin\Release\NetShield.exe -c ..\rule\HTTP\vulsig-http-sample-0.1.xml -t HttpSample.tcpdump
echo.

echo Analyze raw tcpdump trace using the parser generated by UltraPac
echo.
..\bin\Release\NetShield.exe -c ..\rule\HTTP\vulsig-http-sample-0.1.xml -t HttpSample.tcpdump --use-pac
echo.

echo Do tcp reassembling first and then analyze application-layer data
echo.
if exist sample.rsm del sample.rsm
..\bin\Release\TCPReassembler.exe HttpSample.tcpdump HttpSample.rsm
..\bin\Release\NetShield.exe -c ..\rule\HTTP\vulsig-http-sample-0.1.xml -r HttpSample.rsm
echo.

echo Do tcp reassembling first and then analyze application-layer data using the parser generated by UltraPac
echo.
if exist HttpSample.rsm del HttpSample.rsm
..\bin\Release\TCPReassembler.exe HttpSample.tcpdump HttpSample.rsm
..\bin\Release\NetShield.exe -c ..\rule\HTTP\vulsig-http-sample-0.1.xml -r HttpSample.rsm --use-pac
echo.

echo Analyze raw WINRPC tcpdump trace
echo.
..\bin\Release\NetShield.exe -p winrpc -c ..\rule\WINRPC\vulsig-winrpc-sample-0.1.xml -t WinrpcSample.tcpdump
echo.

echo Analyze raw WINRPC tcpdump trace sequentially
echo.
..\bin\Release\NetShield.exe -p winrpc --seq-match -t WinrpcSample.tcpdump
echo.

echo on
